// svelte/src/App.svelte
<script>
  import Polynomial from './Polynomial.svelte';
  import Display from './Display.svelte';

  let func;

  async function polynomialChanged(event) {
    const p = event.detail;
    func = new Function('x', `return ${p.a} * x * x + ${p.b} * x + ${p.c}`);
  }
</script>

<main>
  <h1>Graphing Calculator</h1>
  <Polynomial on:polynomialChanged={ polynomialChanged }/>
  <Display func={ func }/>
</main>

<style>
main {
  font-family: sans-serif;
}
</style>

// vue/src/App.vue
<template>
  <div id="app">
    <h1>Graphing Calculator (Vue)</h1>
    <Polynomial v-on:polynomial-changed="polynomialChanged"/>
    <Display :func="func"/>
  </div>
</template>

<script>
import Polynomial from './components/Polynomial.vue'
import Display from './components/Display.vue'

export default {
  name: 'App',
  components: {
    Polynomial,
    Display,
  },
  data: function() {
    return {
      func: null,
    }
  },
  methods: {
    polynomialChanged: function(p) {
      this.func = new Function('x', `return ${p.a} * x * x + ${p.b} * x + ${p.c}`);
    }
  },
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
}
</style>
