// vue/src/App.vue
<template>
  <div id="app">
    <h1>Graphing Calculator (Vue)</h1>
    <Polynomial v-on:polynomial-changed="polynomialChanged"/>
    <Display :func="func"/>
  </div>
</template>

<script>
import Polynomial from './components/Polynomial.vue'
import Display from './components/Display.vue'

export default {
  name: 'App',
  components: {
    Polynomial,
    Display,
  },
  data: function() {
    return {
      func: null,
    }
  },
  methods: {
    polynomialChanged: function(p) {
      this.func = new Function('x', `return ${p.a} * x * x + ${p.b} * x + ${p.c}`);
    }
  },
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
}
</style>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { Polynomial } from '../polynomial';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Graphing Calculator (Angular)';
  func: (x: number) => number;

  polynomialChanged(p) {
    this.func = new Function('x', `return ${p.a} * x * x + ${p.b} * x + ${p.c}`) as (x: number) => number;
  }
}

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    margin: 8px 0;
  }

  p {
    margin: 0;
  }

  a,
  a:visited,
  a:hover {
    color: #1976d2;
    text-decoration: none;
  }

  a:hover {
    color: #125699;
  }
</style>

<h1>{{title}}</h1>

<app-polynomial (polynomialChanged)="polynomialChanged($event)"></app-polynomial>
<app-display [func]="func"></app-display>
